services:
  db:
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=0202
      - MYSQL_DATABASE=markit
      - MYSQL_USER=sad
      - MYSQL_PASSWORD=0202
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin" , "ping" , "-h" , "localhost"]
      interval: 1m30s
      timeout: 30s
      retries: 5
      start_period: 30s

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - DATABASE_URL=mysql://root:0202@db:3306/markit
    volumes:
      - ./server:/app/server
      - ./frontend:/app/frontend
    command: >
       sh -c "bun run docker && bun prod/index.js"
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure:4


volumes:
  mysql-data:
